services:
  provision:
    environment:
      STORAGE_ADMIN_PASSWORD: "${STORAGE_ADMIN_PASSWORD}"
    volumes:
      - "{{sdk_root}}/packages/storage/deploy/db/provisioning/roles.sql:/provision/setup/50-storage-roles.sql:ro"
