#!/usr/bin/env bash
# Copyright (C) 2026 Fiber
#
# This file is part of scribe and is made available under the PolyForm Shield
# License 1.0.0. The full terms are in the LICENSE file at the root of this
# repository, and at https://polyformproject.org/licenses/shield/1.0.0
#
# What you may do:
# - Use this software for any purpose, including commercially, and build and
#   sell your own products on top of it.
# - Change it, and create new works based on it.
# - Distribute copies of it, with or without your changes.
#
# The one thing you may not do:
# - Use it to provide any product that competes with scribe, or with any
#   product Fiber or its affiliates provide using scribe. Products compete
#   even when they are offered free of charge, through a different kind of
#   interface, or for a different technical platform.
#
# If you pass this software on:
# - Anyone who receives any part of it from you must also receive these terms,
#   or the URL above, together with the "Required Notice" line carried by the
#   LICENSE file.
#
# Disclaimer:
# AS FAR AS THE LAW ALLOWS, THIS SOFTWARE COMES AS IS, WITHOUT ANY WARRANTY OR
# CONDITION, AND THE LICENSOR WILL NOT BE LIABLE TO YOU FOR ANY DAMAGES ARISING
# OUT OF THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY KIND OF
# LEGAL CLAIM.
#
# This header is a summary written for convenience. Where it differs from the
# LICENSE file, the LICENSE file governs.

set -euo pipefail

EXTENSIONS="ts tsx js mjs cjs jsx dart go c h cpp hpp cc rs java kt swift proto php py sh rb sql"
EXCLUDED="node_modules .git .dart_tool __pycache__ gen examples templates"
SCAN_LINES=60

COPYRIGHT="Copyright (C) 2026 Fiber"
LICENSE_NAME="PolyForm Shield"
GENERATED="auto-generated|@generated|DO NOT EDIT|Generated by the protocol buffer compiler|generated file - do not edit"

find_arguments=()
for extension in $EXTENSIONS; do
  find_arguments+=(-o -name "*.$extension")
done
unset 'find_arguments[0]'

prune_arguments=()
for directory in $EXCLUDED; do
  prune_arguments+=(-name "$directory" -o)
done

listing=$(mktemp)
trap 'rm -f "$listing"' EXIT

find . \( "${prune_arguments[@]}" -false \) -prune -o -type f \( "${find_arguments[@]}" \) -print \
  | grep -v -E '\.(g|pb|pbenum|pbjson|pbserver)\.dart$' \
  | grep -v -E '_pb\.ts$' \
  | sort > "$listing"

if [ ! -s "$listing" ]; then
  echo "No source file to check"
  exit 0
fi

report=$(awk -v scan="$SCAN_LINES" -v copyright="$COPYRIGHT" -v license="$LICENSE_NAME" -v generated="$GENERATED" '
  NR == FNR { all[++total] = $0; next }
  FNR <= scan {
    if (index($0, copyright)) hasCopyright[FILENAME] = 1
    if (index($0, license)) hasLicense[FILENAME] = 1
    if ($0 ~ generated) isGenerated[FILENAME] = 1
  }
  END {
    missing = 0; checked = 0; skipped = 0
    for (i = 1; i <= total; i++) {
      file = all[i]
      if (file in isGenerated) { skipped++; continue }
      checked++
      if (!(file in hasCopyright)) { print "MISSING  " file; missing++; continue }
      if (!(file in hasLicense)) {
        print "STALE    " file
        print "         has a copyright line but does not name the license"
        missing++
      }
    }
    print "@" missing "\t" checked "\t" skipped
  }
' "$listing" $(cat "$listing"))

summary=$(printf '%s\n' "$report" | grep '^@' | tail -1)
printf '%s\n' "$report" | grep -v '^@' || true

missing=$(printf '%s' "$summary" | cut -f1 | tr -d '@')
checked=$(printf '%s' "$summary" | cut -f2)
skipped=$(printf '%s' "$summary" | cut -f3)

if [ "$missing" -gt 0 ]; then
  cat >&2 <<EOF

$missing of $checked source files are missing the license header.

Every source file carries it, in the comment syntax of its language: // for
TypeScript, Dart, Go, C and friends, # for shell, Python and Ruby, -- for SQL.
Copy the header from a neighbouring file of the same language, or from
CONTRIBUTING.md.

The header goes at the very top, except in a file that starts with a shebang,
where it goes on the line after it.
EOF
  exit 1
fi

echo ""
echo "Checked $checked source files, all carry the license header"
echo "Skipped $skipped generated files"
