services:
  opensearch:
    security_opt: ["no-new-privileges:true"]
    cap_drop: ["ALL"]
    cap_add: ["IPC_LOCK"]
    networks: ["data"]
    profiles: ["search"]
    image: "opensearchproject/opensearch:2.19.1"
    restart: "unless-stopped"
    volumes:
      - "{{sdk_root}}/opensearch:/usr/share/opensearch/data:Z"
    environment:
      cluster.name: "{{app_name_snake}}"
      node.name: "opensearch"
      discovery.type: "single-node"
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -sf http://127.0.0.1:9200/_cluster/health | grep -v ''"status":"red"''',
        ]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "60s"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
