name: scribe-realtime-e2e

services:
  db:
    container_name: "scribe-realtime-e2e-db"
    ports: ["55434:5432"]
    volumes:
      - "../../realtime/db/provisioning/realtime.sql:/docker-entrypoint-initdb.d/init-scripts/96-realtime.sql:Z"
      - "./.postgres:/var/lib/postgresql/data:Z"
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf",
        "-c",
        "log_min_messages=fatal",
        "-c",
        "max_connections=100",
        "-c",
        "shared_buffers=256MB",
        "-c",
        "effective_cache_size=1GB",
      ]

  rest:
    container_name: "scribe-realtime-e2e-rest"
    ports: ["53002:3000"]

  db-migrate:
    container_name: "scribe-realtime-e2e-db-migrate"

  realtime:
    container_name: "realtime-dev.scribe-realtime-e2e"
    ports: ["54001:4000"]

  realtime-init:
    container_name: "scribe-realtime-e2e-realtime-init"
    volumes:
      - "../db/init/realtime.sql:/realtime-init-project.sql:ro,Z"

volumes:
  db-config: null
