services:
  provision:
    environment:
      AUTH_ADMIN_PASSWORD: "${AUTH_ADMIN_PASSWORD}"
    volumes:
      - "{{sdk_root}}/packages/auth/deploy/db/provisioning/roles.sql:/provision/setup/50-auth-roles.sql:ro"
      - "{{sdk_root}}/packages/auth/deploy/db/provisioning/jwt.sql:/provision/setup/60-auth-jwt.sql:ro"
