// Copyright (C) 2026 Fiber
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
// - Combine it with files under any other licence, proprietary ones included,
//   and licence that larger work on your own terms.
//
// What you must do in return:
// - Keep this notice on every file you received it on.
// - Publish, under these same terms, the source of every file covered by them
//   that you distribute, including the ones you changed, so that whoever
//   receives your version can obtain that source.
// - Leave Fiber out of it: the name "Fiber", its branding, its logos and its
//   trademarks may not be used to endorse or promote what you build, and this
//   licence grants no right to them.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
// OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
// NON-INFRINGEMENT. IN NO EVENT SHALL FIBER BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT
// LIMITED TO LOSS OF USE, DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT
// OF OR RELATED TO THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY
// KIND OF LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

syntax = "proto3";

package scribe.clients.database.v1;

import "scribe/protocol/common.proto";

enum Operation {
  OPERATION_UNSPECIFIED = 0;
  OPERATION_SELECT = 1;
  OPERATION_INSERT = 2;
  OPERATION_UPDATE = 3;
  OPERATION_UPSERT = 4;
  OPERATION_DELETE = 5;
  OPERATION_RPC = 6;
}

enum FilterOperator {
  FILTER_OPERATOR_UNSPECIFIED = 0;
  FILTER_OPERATOR_EQ = 1;
  FILTER_OPERATOR_NEQ = 2;
  FILTER_OPERATOR_GT = 3;
  FILTER_OPERATOR_GTE = 4;
  FILTER_OPERATOR_LT = 5;
  FILTER_OPERATOR_LTE = 6;
  FILTER_OPERATOR_LIKE = 7;
  FILTER_OPERATOR_ILIKE = 8;
  FILTER_OPERATOR_IN = 9;
  FILTER_OPERATOR_IS = 10;
  FILTER_OPERATOR_CONTAINS = 11;
  FILTER_OPERATOR_CONTAINED_BY = 12;
  FILTER_OPERATOR_OVERLAPS = 13;
  FILTER_OPERATOR_TEXT_SEARCH = 14;
}

message Filter {
  string column = 1;
  FilterOperator operator = 2;
  scribe.v1.Json value = 3;
  bool negated = 4;
}

message FilterGroup {
  repeated Filter filters = 1;
  repeated FilterGroup groups = 2;
  bool disjunction = 3;
}

message Order {
  string column = 1;
  bool descending = 2;
  bool nulls_first = 3;
}

message Range {
  uint32 limit = 1;
  uint32 offset = 2;
}

message Query {
  string table = 1;
  Operation operation = 2;
  repeated string select = 3;
  FilterGroup where = 4;
  repeated Order order = 5;
  Range range = 6;
  bool single = 7;
  bool count_exact = 8;
  scribe.v1.Json payload = 9;
  repeated string on_conflict = 10;
  string rpc_name = 11;
  scribe.v1.Json rpc_args = 12;
}

message QueryResult {
  scribe.v1.Json data = 1;
  uint64 count = 2;
  scribe.v1.Failure error = 3;
}

message QueryBatch {
  repeated Query queries = 1;
}

message QueryResultBatch {
  repeated QueryResult results = 1;
}

service Database {
  rpc Execute(Query) returns (QueryResult);
  rpc ExecuteBatch(QueryBatch) returns (QueryResultBatch);
}
