// Copyright (C) 2026 Fiber
//
// This file is part of scribe and is made available under the PolyForm Shield
// License 1.0.0. The full terms are in the LICENSE file at the root of this
// repository, and at https://polyformproject.org/licenses/shield/1.0.0
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
//
// The one thing you may not do:
// - Use it to provide any product that competes with scribe, or with any
//   product Fiber or its affiliates provide using scribe. Products compete
//   even when they are offered free of charge, through a different kind of
//   interface, or for a different technical platform.
//
// If you pass this software on:
// - Anyone who receives any part of it from you must also receive these terms,
//   or the URL above, together with the "Required Notice" line carried by the
//   LICENSE file.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE COMES AS IS, WITHOUT ANY WARRANTY OR
// CONDITION, AND THE LICENSOR WILL NOT BE LIABLE TO YOU FOR ANY DAMAGES ARISING
// OUT OF THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY KIND OF
// LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

// deno-lint-ignore-file no-explicit-any
import "@scribe/core/testing/settings.ts";

import { Tables } from "@scribe/foundation/src/database/gen/tables.ts";
// gen/tables.ts is generated by `koko gen code` and does not re-export TablesBase.
import { TablesBase } from "@scribe/core/clients/database/tables.ts";
import { database } from "@scribe/foundation/src/database/database.ts";
import type { InstalledMock } from "@scribe/core/testing/install.ts";
import type { FakePostgrestSeed } from "@scribe/core/testing/database/fake_postgrest.ts";
import { createDatabaseMock, type DatabaseMock } from "./database.ts";

// `database` is not a getter object but a `Tables` instance: its table methods live
// on the prototype. We therefore install one own property per method, shadowing
// the prototype one and delegating to the fake `restore()` deletes them and the
// prototype reappears.
// `rpc` lives on TablesBase.prototype, not on Tables.prototype: walking only the
// generated class would leave `database.rpc()` pointing at the real PostgREST client,
// so an endpoint under test would attempt a network call instead of hitting the
// fake. Both prototypes are therefore shadowed.
function _shadowTableMethods(target: object, source: Tables): InstalledMock[] {
  const names = [
    ...new Set([
      ...Object.getOwnPropertyNames(Tables.prototype),
      ...Object.getOwnPropertyNames(TablesBase.prototype),
    ]),
  ].filter(
    (name) => name !== "constructor" && typeof (source as any)[name] === "function",
  );

  return names.map((name) => {
    Object.defineProperty(target, name, {
      value: (...args: unknown[]) => (source as any)[name](...args),
      configurable: true,
      writable: true,
    });
    return {
      restore(): void {
        delete (target as any)[name];
      },
    };
  });
}

export function installDatabaseMock(
  seed: FakePostgrestSeed = {},
): DatabaseMock & InstalledMock {
  const mock = createDatabaseMock(seed);
  const installed: InstalledMock[] = [
    ..._shadowTableMethods(database, mock.service),
  ];

  return Object.assign(mock, {
    restore(): void {
      for (const entry of installed) entry.restore();
    },
  });
}
