// Copyright (C) 2026 Fiber
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
// - Combine it with files under any other licence, proprietary ones included,
//   and licence that larger work on your own terms.
//
// What you must do in return:
// - Keep this notice on every file you received it on.
// - Publish, under these same terms, the source of every file covered by them
//   that you distribute, including the ones you changed, so that whoever
//   receives your version can obtain that source.
// - Leave Fiber out of it: the name "Fiber", its branding, its logos and its
//   trademarks may not be used to endorse or promote what you build, and this
//   licence grants no right to them.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
// OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
// NON-INFRINGEMENT. IN NO EVENT SHALL FIBER BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT
// LIMITED TO LOSS OF USE, DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT
// OF OR RELATED TO THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY
// KIND OF LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

syntax = "proto3";

package scribe.clients.auth.v1;

import "scribe/protocol/common.proto";

message AccountRequest {
  string account_id = 1;
  string role = 2;
}

message Account {
  string id = 1;
  string role = 2;
  string email = 3;
  string phone = 4;
  bool email_verified = 5;
  bool phone_verified = 6;
  int64 created_at = 7;
  Ban ban = 8;
  scribe.v1.Json folded = 9;
}

message AccountResult {
  Account account = 1;
  scribe.v1.Failure error = 2;
}

message Ban {
  int64 since = 1;
  int64 until = 2;
  string reason = 3;
}

message BanRequest {
  string account_id = 1;
  string role = 2;
  int64 for_ms = 3;
  string reason = 4;
}

message BanResult {
  scribe.v1.Failure error = 1;
}

message BanListRequest {
  string role = 1;
}

message ListedBan {
  string account_id = 1;
  Ban ban = 2;
}

message BanListResult {
  repeated ListedBan bans = 1;
  scribe.v1.Failure error = 2;
}

message DeviceRequest {
  string account_id = 1;
  string role = 2;
  string device_id = 3;
}

message Device {
  string id = 1;
  string device_id = 2;
  string client = 3;
  string os = 4;
  string model = 5;
  string app_version = 6;
  bool is_physical_device = 7;
  string device_category = 8;
  bool trusted = 9;
  string ip = 10;
  string city = 11;
  string country = 12;
  int64 created_at = 13;
  int64 seen_at = 14;
}

message DeviceListResult {
  repeated Device devices = 1;
  scribe.v1.Failure error = 2;
}

message KickResult {
  bool kicked = 1;
  scribe.v1.Failure error = 2;
}

message ValidateRequest {
  string password = 1;
  string email = 2;
  string phone = 3;
}

message ValidateResult {
  bool valid = 1;
  repeated string violations = 2;
}

message RoleListRequest {}

message RoleListResult {
  repeated Role roles = 1;
}

message Role {
  string name = 1;
  repeated string channels = 2;
  string created = 3;
}

service Auth {
  rpc GetAccount(AccountRequest) returns (AccountResult);
  rpc DeleteAccount(AccountRequest) returns (BanResult);

  rpc Ban(BanRequest) returns (BanResult);
  rpc Unban(AccountRequest) returns (BanResult);
  rpc ListBans(BanListRequest) returns (BanListResult);

  rpc ListDevices(DeviceRequest) returns (DeviceListResult);
  rpc KickDevice(DeviceRequest) returns (KickResult);
  rpc KickAllDevices(DeviceRequest) returns (KickResult);

  rpc ListRoles(RoleListRequest) returns (RoleListResult);
  rpc Validate(ValidateRequest) returns (ValidateResult);
}
